language: node_js
node_js:
  - "node"
before_script:
  - npm install -g firebase-tools
script:
  - npm test
after_success: cd Firebase && firebase deploy --token $FIREBASE_TOKEN

//$FIREBASE_TOKEN must contains full firebase token (firebase login:ci) including "1/" part !!!
//And then be declared in environnement varialbe using Travis Web site

